version: '3'
services:
  react-app:
    # stdin_open: true
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:8000'
    volumes:
      - ./src:/app/src:ro
    environment:
      - REACT_APP_NAME=Kim Jisoo
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env
