version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:8000'
    volumes:
      - ./src:/app/src:ro
    environment:
      - REACT_APP_NAME=Kim Jisoo Dev
      - CHOKIDAR_USEPOLLING=true
